### ISSUE TITLE
Different ordered result returned when change the max value in search API.

### ISSUE THREAD

**Issue by stonega** [Podcastindex-org/search#4]
According to the document, change the max value in request will Limits the number of results. The issue is that the result from max 10 and max 20 have different order. The first ten feeds of max 20 is not the same as feed of max 10. This is not expected because the results is ordered by the last-released episode as doc described.
My test search term is `verge` .

Thanks for the great podcast search engine, so exited!

**Comment by daveajones** [comment]
That's odd. Let me check it.

**Comment by daveajones** [comment]
Should be fixed now.  Sphinx doesn't have a sense of order, so the LIMIT needed to be in the lookup function, not the search itself.

**Comment by stonega** [comment]
Thanks for the quick fix!
